import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { Nav } from "@/components/navbar/nav"
import { Providers } from "./provider"
import "./globals.css";
import { SearchProvider } from "@/components/navbar/context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" suppressHydrationWarning lang="en" >
      <head />
      <body className={inter.className}>
        <Providers>
          <SearchProvider>
            <Nav />
            <main>
              {children}
            </main>
          </SearchProvider>
        </Providers>
      </body>
    </html >
  );
}
